# Generated by Django 4.2.7 on 2026-04-15 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, help_text='Lipana transaction ID returned on STK push initiation', max_length=100, null=True, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, help_text='Lipana/Safaricom checkout request ID', max_length=100, null=True)),
                ('mpesa_receipt', models.CharField(blank=True, help_text='M-Pesa receipt number (only present on success)', max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payments_mp_transac_f38b62_idx'), models.Index(fields=['checkout_request_id'], name='payments_mp_checkou_a6f836_idx'), models.Index(fields=['status'], name='payments_mp_status_dfa634_idx')],
            },
        ),
    ]
