# Generated by Django 4.2.7 on 2026-04-09 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('item_count', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.TextField(blank=True, default='')),
                ('product_slug', models.SlugField(blank=True, default='', max_length=255)),
                ('variant_id', models.UUIDField(blank=True, null=True)),
                ('variant_name', models.CharField(blank=True, default='', max_length=200)),
                ('variant_info', models.JSONField(default=dict)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
    ]
