# Generated by Django 4.2.7 on 2026-04-09 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('product_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('short_description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category_name', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('main_image', models.TextField(blank=True, default='')),
                ('additional_images', models.JSONField(default=list)),
                ('stock', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('track_quantity', models.BooleanField(default=True)),
                ('continue_selling', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('meta_title', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('specifications', models.JSONField(default=dict)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('view_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=200)),
                ('ip_address', models.CharField(blank=True, default='', max_length=50)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
            ],
            options={
                'db_table': 'product_views',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.TextField(blank=True, default='')),
                ('attributes', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=200)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'db_table': 'product_reviews',
            },
        ),
    ]
